# PCA VS LDA

This note book provides idea about the PCA and LDA concepts and what is the difference between them and how and where to use these techniques in practical usecases 

In one of the Kaggle submission we had House sales prediction system which was having 80 Features and operating with all of them was not so easy so in that case we can use this 

In [134]:
import numpy as np
import pandas as pd

In [135]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)

In [136]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [137]:
X = dataset.drop('Class', 1)
y = dataset['Class']

In [138]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# SCALING

In [139]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# PCA example

In [140]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [141]:
explained_variance = pca.explained_variance_ratio_

# PCA 1ST COMPONENT

In [142]:
from sklearn.decomposition import PCA
def pca_first_component(X_train,X_test):
    pca = PCA(n_components=1)
    X_train = pca.fit_transform(X_train)
    X_test = pca.transform(X_test)
    return X_train,X_test

# PCA 1st and 2nd component

In [143]:
from sklearn.decomposition import PCA
def pca_first_second_component(X_train,X_test):
    pca = PCA(n_components=2)
    X_train = pca.fit_transform(X_train)
    X_test = pca.transform(X_test)
    return X_train,X_test

# RANDOM FOREST CLASSIFICATION USING THE PCA

In [144]:
from sklearn.ensemble import RandomForestClassifier
def random_forest_classifier(X_train, y_train,X_test):
    classifier = RandomForestClassifier(max_depth=2, random_state=0)
    classifier.fit(X_train, y_train)

    # Predicting the Test set results
    y_pred = classifier.predict(X_test)
    return y_pred

In [145]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
def confusion_matrix_result(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    print('Accuracy')
    print(accuracy_score(y_test, y_pred))

# 1ST COMPONENT RESULTS 

In [146]:
X_train_1,X_test_1 = pca_first_component(X_train,X_test)
y_pred = random_forest_classifier(X_train_1,y_train,X_test_1)
confusion_matrix_result(y_test,y_pred)

[[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]
Accuracy
0.9333333333333333


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


# 2ND COMPONENT RESULTS 

In [147]:
X_train_2,X_test_2 = pca_first_second_component(X_train,X_test)
y_pred = random_forest_classifier(X_train_2,y_train,X_test_2)
confusion_matrix_result(y_test,y_pred)

[[11  0  0]
 [ 0 10  3]
 [ 0  2  4]]
Accuracy
0.8333333333333334


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
